#
# nort release configuration 
#
qualification:

build:

publish:
  local.artifact.repository.root: ${M2}
  release.tag: <project-name>-release-${current.version}

install:
  installation.directory: ${RUNTIME_DIR}/gld/extensions

