#
# gld release configuration 
#
qualification:

  os.command.to.get.installed.version: gld version

build:

publish:
  local.artifact.repository.root: ${M2}
  release.tag: gld-release-${current.version}

install:
  installation.directory: ${RUNTIME_DIR}

